FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:256 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0xc0028c5e 0x80e1fd9
Translation of call stack:
In kernel.o:
0xc0028c5e: debug_panic (.../../lib/kernel/debug.c:38)
0x080e1fd9: (unknown)
